# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift.obj c
osx_image: xcode10.0
xcode_project: openxc-ios-framework.xcodeproj
xcode_scheme: openxc-ios-framework
xcode_sdk: iphonesimulator11.4

branches:
- master
- next

script:
#- xcodebuild clean build test -project openxc-ios-framework.xcodeproj -scheme openxc-ios-framework -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.4'  ONLY_ACTIVE_ARCH=NO
- xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty


# cache: cocoapods
# podfile: Example/Podfile
# before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod repo update
#- pod install --project-directory=Example

#script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint --allow-warnings
# -- set -o pipefail &&

