# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage


language: swift
osx_image: xcode10.2
xcode_project:  Example/openxcframework.xcworkspace
xcode_scheme: openxc-ios-framework
xcode_sdk: iphonesimulator12.0
os: osx

branches:
- master
- next




#script:
#- xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty


# cache: cocoapods
# podfile: Example/Podfile
# before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod repo update
#- pod install --project-directory=Example

script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint --allow-warnings
# -- set -o pipefail &&
pod trunk push -verbose

# stages:
# - name: lint
# if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
# - name: compile
# if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
# - name: test
# if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
# - name: deploy
# if: branch =~ ^\d+\.\d+\.\d+$
# - stage: Deploy to cocoapods

# script: | 
# pod trunk push -verbose | ruby -e 'ARGF.each{print "." }'



