# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10.2
xcode_workspace:  Example/openxcframework.xcworkspace
xcode_scheme: openxcframework-Example
xcode_sdk: iphonesimulator12.2
os: osx
podfile: Example/

stages:
- name: build
- name: deploy
  if: branch = master
  
jobs:
  - stage: build
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod deintegrate
    - pod install
    - cd ../
    - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO
    
  - stage: deploy
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod install
    - cd ../
    - pod trunk push --verbose | ruby -e 'ARGF.each{ print "." }'
    
#- pod spec lint openxcframework.podspec  --allow-warnings
#- pod trunk push openxcframework.podspec --allow-warnings -verbose | ruby -e 'ARGF.each{print "." }'




