# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10.2
xcode_workspace:  Example/openxcframework.xcworkspace
xcode_scheme: openxcframework-Example
xcode_sdk: iphonesimulator12.2
os: osx
podfile: Example/

before_script:
- gem install cocoapods
- pod repo update
- cd Example/
- pod install ProtocolBuffers-Swift
- cd ../

jobs:
  include:
  - stage: setup

stages:
- name: setup
- name: build
- name: deploy
  if: branch = master

- stage: setup
  script:
  - echo "DOES IT EVEN WORK\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

- stage: build
  script:
  - gem install cocoapods
  - pod repo update
  - cd Example/
  - pod install ProtocolBuffers-Swift
  - cd ../
  - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty
    
- stage: deploy
  script: |
    pod trunk push --verbose | ruby -e 'ARGF.each{ print "." }'
    
#- pod spec lint openxcframework.podspec  --allow-warnings
#- pod trunk push openxcframework.podspec --allow-warnings -verbose | ruby -e 'ARGF.each{print "." }'




